Ensure action fails when used so users are pointed to updated docs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,7 @@
 name: Actions 😎
 on:
-  pull_request: {}
-  push: { branches: [main] }
+  pull_request:
+  push:
 
 jobs:
   tests:
@@ -11,7 +11,7 @@ jobs:
       - uses: actions/checkout@v1
       - uses: actions/setup-node@v1
         with:
-          node-version: 12.x
+          node-version: 20.x
       - run: yarn
       - run: yarn lint
       - run: yarn test
@@ -21,30 +21,20 @@ jobs:
   requestManualActivationFile:
     name: Request manual activation file 🔑
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        unityVersion:
-          - 2018.4.15f1
-          - 2019.2.11f1
-          - 2019.2.14f1
-          - 2019.2.17f1
-          # - 2020.1.0a15
     steps:
       # Checkout repository (required to test local actions)
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       # Request manual activation file
       - name: Request manual activation file
         id: getManualLicenseFile
+        continue-on-error: true
         uses: ./
-        with:
-          unityVersion: ${{ matrix.unityVersion }}
 
-      # Upload artifact (Unity_v20XX.X.XXXX.alf)
-      - name: Expose as artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
-          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
+      - name: Verify error
+        run: |
+          if [ "${{ steps.getManualLicenseFile.outcome }}" != "failure"  ]; then
+            echo "Expected failure, got ${{ steps.getManualLicenseFile.outcome }}"
+            exit 1
+          fi
